### ISSUE TITLE
json-schema and snippets

### ISSUE THREAD

**Issue by noahlaux** [json-e/json-e#382]
Hi guys, 

I got tired of compiler errors and thought about if it was possible to describe the operators in a json-schema to get real time validation in supported IDEs.

it proved quite possible and I tried to create most of the operators and even created some snippets for vs code. so you can write stuff like `let` or `if` and it will provide you with a couple of snippet examples.

Furthermore, you get inline errors, description of tag features on hover much more.

I really like the feel of where this is going, what do you think about the idea?

I put the schema here together with a little test json document showing the approach https://www.jsonschemavalidator.net/s/LUoae88v

I'd like to try to match the builtin functions in `$eval` and expanded strings, so you can have errors when providing wrong arguments :O.

If you want the full experience (which I find particularly awesome), in vscode you can install the [red hat YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension and add something like this in your .vscode settings:

```json
"yaml.schemas": {
    "../jsone-schema.json": ["yourfile.yaml"]
}
```

![alt text](https://media.giphy.com/media/o0lVNWMniaRP3t8ODE/giphy.gif)

### schema

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["object", "array", "boolean", "integer", "null", "number", "string"],
  "additionalProperties": { "$ref": "#" },
  "definitions": {
    "stringKeys": {
      "propertyNames": {
        "description": "property should be a string",
        "anyOf": [{ "pattern": "[^0-9]" }]
      }
    }
  },
  "patternProperties": {
    "^\\$map": { "type": ["object", "array"] },
    "^\\$let": {
      "type": "object",
      "title": "$let operator",
      "description": "The $let operator evaluates an expression using a context amended with the given values. It is analogous to the Haskell where clause."
    },
    "^\\$match": {
      "type": "object",
      "$ref": "#/definitions/stringKeys",
      "title": "$match operator",
      "description": "The $match operator is not dissimilar to pattern matching operators. It gets an object, in which every key is a string expression(s) to evaluate to true or false based on the context. The result will be an array of things (all types are supported) that were values corresponding to the keys that were evaluated to true. The order of the things in the array will be arbitrary. If there are no matches, the result is an empty array."
    },
    "^\\$switch": {
      "type": "object",
      "$ref": "#/definitions/stringKeys",
      "title": "$switch operator",
      "description": "The $switch operator behaves like a combination of the $if and $match operator for more complex boolean logic. It gets an object, in which every key is a string expression(s), where at most one must evaluate to true and the remaining to false based on the context. The result will be the value corresponding to the key that were evaluated to true.\nIf there are no matches, the result is either null or if used within an object or array, omitted from the parent object."
    },
    "^\\$merge": {
      "type": "array",
      "title": "$merge operator",
      "description": "The $merge operator merges an array of objects, returning a single object that combines all of the objects in the array, where the right-side objects overwrite the values of the left-side ones."
    },
    "^\\$mergeDeep": {
      "type": "array",
      "title": "$mergeDeep operator",
      "description": "The $mergeDeep operator is like $merge, but it recurses into objects to combine their contents property by property. Arrays are concatenated."
    },
    "^\\$sort": {
      "type": "array",
      "title": "$sort operator",
      "description": "The $sort operator sorts the given array. It takes a by(var) property which should evaluate to a comparable value for each element. The by(var) property defaults to the identity function."
    },
    "^\\$reverse": {
      "type": "array",
      "title": "$reverse operator",
      "description": "The $reverse operator simply reverses the given array."
    },
    "^\\$eval": {
      "type": "string",
      "title": "$eval operator",
      "description": "The $eval operator evaluates the given expression and is replaced with the result of that evaluation. Unlike with string interpolation, the result need not be a string, but can be an arbitrary data structure."
    },
    "^\\$if": {
      "type": "string",
      "title": "$if - then - else",
      "description": "The $if operator supports conditionals. It evaluates the given value, and replaces itself with the then or else properties. If either property is omitted, then the expression is omitted from the parent object."
    },
    "^\\$flatten": {
      "type": "array",
      "title": "$flatten operator",
      "description": "The $flatten operator flattens an array of arrays into one array."
    },
    "^\\$flattenDeep": {
      "type": "array",
      "title": "$flattenDeep operator",
      "description": "The $flattenDeep operator deeply flattens an array of arrays into one array."
    },
    "^\\$json": {
      "type": "array",
      "title": "$json operator",
      "description": "The $json operator formats the given value as JSON with sorted keys. It does not evaluate the value (use $eval for that). While this can be useful in some cases, it is an unusual case to include a JSON string in a larger data structure."
    },
    "^\\$fromNow": { "type": "string" }
  },
  "dependencies": {
    "$map": {
      "properties": {
        "$map": {}
      },
      "patternProperties": {
        "^each\\([^0-9]+\\)$": { "type": "object" }
      },
      "minProperties": 2,
      "additionalProperties": false
    },
    "$let": {
      "properties": {
        "$let": {},
        "in": { "type": "object" }
      },
      "required": ["in"],
      "additionalProperties": false
    },
    "$if": {
      "properties": {
        "$if": {},
        "then": {
          "title": "then operator",
          "description": "Used in combination with the $if operator"
        },
        "else": {
          "title": "else operator",
          "description": "Used in combination with the $if operator"
        }
      },
      "anyOf": [{ "required": ["then"] }, { "required": ["else"] }],
      "additionalProperties": false
    },
    "$sort": {
      "properties": {
        "$sort": {}
      },
      "patternProperties": {
        "^by\\([^0-9]+\\)$": { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "defaultSnippets": [
    {
      "label": "if - then",
      "description": "This is so good",
      "body": { "\\$if": "${1:a > 1}", "then": "${2:a}" }
    },
    {
      "label": "if - then - else",
      "body": { "\\$if": "${1:a > 1}", "then": "${2:a}", "else": "${3:b}" }
    },
    {
      "label": "if - else",
      "body": { "\\$if": "${1:a > 2}", "else": "${2:a}" }
    },
    {
      "label": "$let - in",
      "body": { "\\$let": { "${1:a}": "${2:1}" }, "in": { "${3:b}": "${4:\\${$1\\}}" } }
    },
    {
      "label": "$let - in - eval",
      "body": {
        "\\$let": { "${1:a}": "${2:1}" },
        "in": { "${3:b}": { "\\$eval": "${4:\\${$1\\}}" } }
      }
    },
    {
      "label": "$switch",
      "body": {
        "\\$switch": { "\"${1:a > 1}\"": "${2:big}" }
      }
    },
    {
      "label": "$merge",
      "body": {
        "\\$merge": [{ "${1:a}": "${2:1}" }, { "${3:b}": "${4:2}" }]
      }
    }
  ]
}

```

### test yaml file

```yaml
merge:
  'correct':
    $merge:
      - a: 1
      - b: 2
      - c: 3

  'wrong':
    1:
      $merge: 1
    2:
      $merge:
        a: 1

match:
  'correct':
    1:
      $match:
        'a > 1': a
    2:
      $match:
        'a > 1': a
        'b < 1': b

  'wrong':
    1:
      $match:
    2:
      $match: 1
    3:
      $match:
        1: a

switch:
  'correct':
    1:
      $switch:
        'a > 1': a
    2:
      $switch:
        'a > 1': a
        'b < 1': b

  'wrong':
    1:
      $switch:
    2:
      $switch: 1
    3:
      $switch:
        1: a

let:
  'correct':
    $let:
      some: 1
    in:
      mok: 1

  'wrong':
    1:
      $let:
    2:
      $let: 1
    3:
      $let:
        a: 1
    4:
      $let:
        a: 1
      in: 1
    5:
      $let:
        a: 1
      in:
        a: a
      extra: 1

if:
  'correct':
    1:
      $if: a > 1
      then: a
    2:
      $if: a > 1
      else: b
    3:
      $if: a > 1
      then: a
      else: b

  'wrong':
    1:
      $if:
    2:
      $if: 1
    3:
      $if: a > 1
    4:
      $if: a > 1
      then: a
      extra: 1

flatten:
  'correct':
    $flatten: [1, 2, 3]

  'wrong':
    1:
      $flatten: 1
    2:
      $flatten:
        a: 1

flattenDeep:
  'correct':
    $flattenDeep: [1, 2, 3]

  'wrong':
    1:
      $flattenDeep: 1
    2:
      $flattenDeep:
        a: 1

sort:
  'correct':
    1:
      $sort: [1]
    2:
      $sort: [{ a: 2 }, { a: 1 }, { a: 3 }]
      by(x): 'x.a'
    3:
      $sort: [{ a: 2 }, { a: 1 }, { a: 3 }]
      by(long): 'long.a'

  'wrong':
    1:
      $sort: 1
    2:
      $sort:
        a: 1
    3:
      $sort: [{ a: 2 }, { a: 1 }, { a: 3 }]
      by(x): 1
    4:
      $sort: [{ a: 2 }, { a: 1 }, { a: 3 }]
      by(): 'x.a'
    5:
      $sort: [{ a: 2 }, { a: 1 }, { a: 3 }]
      by(1): 'x.a'
    6:
      $sort: [{ a: 2 }, { a: 1 }, { a: 3 }]
      by: 'x.a'

map:
  'correct':
    1:
      $map: [1, 2]
      each(x):
        a: ${x}
    2:
      $map: [1, 2]
      each(longname):
        a: ${longname}
    3:
      $map: { a: 1, b: 2 }
      each(x, i):
        a: ${x}

  'wrong':
    1:
      $map: 1
    2:
      $map: [1, 2]
    3:
      $map: [1, 2]
      each: 1
    4:
      $map: [1, 2]
      each(): 1
    5:
      $map: [1, 2]
      each(1):
        a: 1
```
