### ISSUE TITLE
Support an `elif` operator

### ISSUE THREAD

**Issue by ahal** [json-e/json-e#454]
I've seen many JSON-e templates get massive and extremely difficult to read (specifically in Taskcluster's `.taskcluster.yml` files). One reason for this is the lack of an `elif` or `elsif` clause which results in patterns like:
```
$if: val == "a"
then: 1
else:
    $if: val == "b"
    then: 2
    else:
         $if: val == "c"
         then: 3
... etc ...
```

Each arm adds another level of indentation and therefore makes the overall file more difficult to understand. I believe an `elif` or `elsif` clause would go a long way towards improving the readability of JSON-e templates.
