### ISSUE TITLE
Support a `default` arm in $switch statements

### ISSUE THREAD

**Issue by ahal** [json-e/json-e#455]
This came out of discussion from issue #454 .

To step back a bit, the problem I'd like to solve is the fact that json-e templates tend to get a lot of indentation when you need to check multiple conditions in an $if statement, e.g:
```
$if: val == "a"
then: foo
else:
  $if: val == "b"
  then: bar
  else: baz
```
Every possible value that needs to be checked requires another level of indentation. Dustin pointed out there is a `$switch` operator which would indeed help solve this in some cases. However, because there is no default arm, there is no easy way to implement an `else` clause with it. The above could be re-written as:
```
$let:
  result:
    $switch:
      val == "a": foo
      val == "b": bar
in:
  $if: defined("result")
  then:
    $eval: result
  else: baz
```
But this is even more verbose and still adds an extra level of indentation. Instead, I propose we implement a `$default` arm of switch statements. The previous examples could then be implemented like:
```
$switch:
  val == "a": foo
  val == "b": bar
  $default: baz
```
