### ISSUE TITLE
Reference the context root

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#478]
Is there a way to reference the context root?

For example, I want to have a template that just wraps the entire context in an object:

```
Template: { foo: { $eval: ??? } }
Context: [ 'an', 'array' ]
Result { foo: [ 'an', 'array' ] }
```

**Comment by djmitche** [comment]
No, that's not supported. That would be a sort of parallel to the [`locals()`](https://docs.python.org/3/library/functions.html#locals) function in Python, which has been problematic for development of the language.  Note that `context` must always be an object, so even if this functionality was supported the above would not be allowed.

The recommended way to handle this is to put the desired value in a variable in the context:
```yaml
template: { foo: { $eval: "elements" } }
context: {elements: [ 'an', 'array' ]
result { foo: [ 'an', 'array' ] }
```
