### ISSUE TITLE
$if expression with built-in doesn't fail

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#488]
Test:

```yaml
title: $if->then->else, function
context: {}
template: {$if: 'min', then: "t", else: "f"}
result: t
```

Why does this not fail?  According to @jonasfj's comment [here](https://github.com/json-e/json-e/issues/158#issuecomment-334585277), the `min` can't be returned.

Or, alternatively, is the non-null function `min` being evaluated as truthy (which feels very weird)?
