### ISSUE TITLE
Confusion about `$json` operator

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#489]
[Docs](https://json-e.js.org/operators.html#json):

> The `$json` operator formats the given value as JSON with sorted keys.

Test:

```yaml
title:    $json alphabetical
context:  {}
template: {$json: {'Z':null,'q':1,'a':{'c':45,'b':['9',8,{}]},'r':true}}
result:   '{"Z":null,"a":{"b":["9",8,{}],"c":45},"q":1,"r":true}'
```

This test shows an _object_ as the value.  Strictly speaking JSON objects are unordered.  I'm not sure what this is testing or if such sorting behavior can be replicated interoperably.

Secondly, there's no documentation on what "sorted" means.  It seems that the following holds true:

- strings are alpha-ordered (is this unicode?  ascii?  culture-sensitive?)
- numbers are value-ordered
- type ordering is ??? (is there type ordering?)

Finally, playing online, it doesn't seem that any sorting is actually occurring:

```yaml
Template: { $json: [1, "b", {key: 1}, false, "a", null, {key: 2}, {}, [1], []]}
Result:   '[1,"b",{"key":1},false,"a",null,{"key":2},{},[1],[]]'
```

I get the items in the array in the same order I put them in; it only converts the value into a JSON string.
