### ISSUE TITLE
Online playground doesn't catch extra `by(x)` args for `$sort`

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#490]
```yaml
Template:
  $sort: [{a: 2}, {a: 1, b: []}, {a: 3}]
  by(per_Mi5t): 'per_Mi5t.a'
  by(x): 'x.b'
```

I would expect this to give either an "additional keys" error or a "object doesn't contain 'b'" error.
