### ISSUE TITLE
`$match` description does not say anything about sorting

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#491]
The [docs for `$match`](https://json-e.js.org/operators.html#match) does say anything about sorting, and yet there is this test:

```yaml
title:    $match, 2 matches, ordered by lexcial sorting of property names
context:  {cond: 3}
template: {$match: {'cond == 3': 2, 'cond == 5': 3, 'cond < 5 && cond > 0': 4, 'true': 17}}
result:   [4, 2, 17]
```

Also, what is the point of sorting in this case?  If anything, shouldn't the results be sorted by the order they are in the template (which, depending on the language you're using, may be indeterministic).
