### ISSUE TITLE
Accessing members of literal values not in docs

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#492]
Test (in the suite):

```yaml
title:    string interpolation with object evaluation
context:  {key: 'world', num: 1}
template: {message: 'hello ${{a: "world"}.a}', 'k-${{a: 1}.a + {a: 0}.a}': true}
result:   {message: 'hello world', 'k-1': true}
```

An expression like `{a: "world"}.a` is not in the documentation anywhere.

You have [Object Property Access](https://json-e.js.org/expressions.html#object-property-access), but it doesn't mention that this can work off of a value literal.

This test took me by surprise.  As this kind of support wasn't planned for, I now have to rework a good portion of my expression parsing to support it.
