### ISSUE TITLE
Difference in behavior between `.` and `[]` when key not found

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#498]
```yaml
title: 'missing property'
context: {key: {a: 1}}
template: {$eval: 'key.b'}
error: 'InterpreterError: object has no property "b"'
---
title: 'missing property by name'
context: {key: {a: 1}}
template: {$eval: 'key["b"]'}
result: null
```

`key.b` should behave the same as `key["b"]`

I realized it's in the docs:

> obj.prop is an error if obj does not have prop, while obj['prop'] will evaluate to null.

But why??!  How is this expected behavior?
