### ISSUE TITLE
`$json` escaping isn't right in a few tests

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#500]
Example:

```yaml
title:    representation of various unicode codepoints are consistent
context:  {}
template: {$json: ["\x10", "Z", "\u0103","\U0001F809"]}
result:   "[\"\\u0010\",\"Z\",\"\u0103\",\"\U0001F809\"]"
```

I understand this is YAML-encoded right now, but `$json` should be outputting valid JSON text, and `\U0001F809` isn't valid JSON text.  It should be encoded using a surrogate pair: `\uD83E\uDC09`.

This would make the test:

```yaml
title:    representation of various unicode codepoints are consistent
context:  {}
template: {$json: ["\x10", "Z", "\u0103","\U0001F809"]}
result:   "[\"\\u0010\",\"Z\",\"\u0103\",\"\\uD83E\\uDC09\"]"
```

The other test this affects is

```yaml
title:    sorting pairs by unicode key strings sorts lexically by codepoint, even with chars above base plane
context:  {}
template: {$json: {"\U0001F809\u732b":'hey', "Z\U00010000P": 1, "\U000E1FFF\u0103": 2, "UaE": 3}}
result:   "{\"UaE\":3,\"Z\U00010000P\":1,\"\U0001F809\u732b\":\"hey\",\"\U000E1FFF\u0103\":2}"
```

**Comment by gregsdennis** [comment]
Similarly, this test is also expecting invalid JSON:

```yaml
title:    sorting pairs by unicode key strings sorts lexically by codepoint
context:  {}
template: {$json: {"\u3347\u0050": 1, "\uE1FF\u0100": 2, "\u0055\u0045": 3}}
result:   "{\"\u0055\u0045\":3,\"\u3347\u0050\":1,\"\uE1FF\u0100\":2}"
```

However, this one doesn't involve a surrogate pair.  In this case, `\uE1FF` is a BMP character.  But when rendered in JSON, it needs to be escaped, so the test should be:

```yaml
title:    sorting pairs by unicode key strings sorts lexically by codepoint
context:  {}
template: {$json: {"\u3347\u0050": 1, "\uE1FF\u0100": 2, "\u0055\u0045": 3}}
result:   "{\"\u0055\u0045\":3,\"\u3347\u0050\":1,\"\\uE1FF\u0100\":2}"
```
