### ISSUE TITLE
How to perform these 2 fucntions in JSON-e

### ISSUE THREAD

**Issue by Era-cell** [json-e/json-e#527]
Hi, I have two functions which I am not able to understand how to run in JSON-e, 
currently it uses Javascript to make the operations:
1. replace() fucntion for the string:
     -- text = "hello"
     -- text.replace("ll", "l")
     - output should be "helo"
2. omit() from an object: currently using lodash from javascript
     -- map = {
                       name: Suprith
                       age: 22     }
     -- omit(map, age) - should give
     - output should be { name: Suprith }
How do I do these operations solely in json-e, help me in this one...
I have posted this as an issue because I did not find the discussions page

**Comment by noahlaux** [comment]
Hi @Era-cell, 

Here's how I'd do it:

1.

template

```yaml
$eval: join(split(text, 'll'), 'l')
```

context
```yaml
text: hello
```

2.

template

```yaml
$map: 
  $eval: data
each(value, key):
  $if: key != 'age'
  then:
    ${key}: ${value} # => name: Suprith
```

context
```yaml
data: 
  name: Suprith
  age: 22
```
