### ISSUE TITLE
Add an aggregator function

### ISSUE THREAD

**Issue by gregsdennis** [json-e/json-e#533]
I can't find a way to perform an aggregation.  We have several functions like `concat()` that can combine arrays of strings, but I don't see how to calculate (e.g.) the product of an array of numbers.

I'd like to propose the `$agg` operator (or `$aggregate` if you prefer to avoid the abbreviation).

Usage is:

```yaml
# template
$agg: [2,3,4,5]
initial: 1
each(current, x): { $eval: 'current * x' }

# result
120
```

Of course, the `each()` function could also take an iterator/index variable as well:

```yaml
# template
$agg: [2,3,4,5]
initial: 1
each(current, x, i): { $eval: 'current * x + i' }

# result
149
```
