### ISSUE TITLE
Bug in Mathematical Calculations 

### ISSUE THREAD

**Issue by kwhitehouse** [json-e/json-e#539]
Hi folks! We're seeing a weird rounding situation with some mathematical calculations. Here's a simple example.

### Template
```
message:
  $eval: 1.17 * 48
anotherMessage:
  $eval: 1.17 * 480
```

### Actual Result
```
message: 56.16
anotherMessage: 561.5999999999999
```

### Expected Result
```
message: 56.16
anotherMessage: 561.6
```

### Playground Screenshot
<img width="785" alt="Screenshot 2024-10-09 at 11 19 46 AM" src="https://github.com/user-attachments/assets/31085c12-19b7-4bf2-99c4-b562b6eb284a">
